// ============================================
// NOUR — 200 Mots Coraniques Complets
// Numéros de versets globaux (1-6236)
// ============================================

const WORDS = [
  // ========== NIVEAU 1 — Les 30 mots les plus fréquents ==========
  { id:1, arabic:"الله", transliteration:"Allāh", meaning:"Allah — Dieu", root:"أله", frequency:2699, verseNumber:1, verseArabic:"بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", verseFr:"Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux", verseRef:"Al-Fatiha, 1:1", tip:"Le mot le plus prononcé dans le Coran — 2699 fois." },
  { id:2, arabic:"رَبّ", transliteration:"Rabb", meaning:"Seigneur — Maître", root:"ربب", frequency:980, verseNumber:2, verseArabic:"الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", verseFr:"Louange à Allah, Seigneur des mondes", verseRef:"Al-Fatiha, 1:2", tip:"Rabb désigne Celui qui crée, nourrit et éduque." },
  { id:3, arabic:"رَحْمَة", transliteration:"Raḥma", meaning:"Miséricorde", root:"رحم", frequency:339, verseNumber:3, verseArabic:"الرَّحْمَٰنِ الرَّحِيمِ", verseFr:"Le Tout Miséricordieux, le Très Miséricordieux", verseRef:"Al-Fatiha, 1:3", tip:"Vient de la même racine que Rahim — une tendresse profonde." },
  { id:4, arabic:"عِلْم", transliteration:"'Ilm", meaning:"Science — Savoir", root:"علم", frequency:854, verseNumber:282, verseArabic:"وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ", verseFr:"Au-dessus de tout détenteur du savoir, il y a un savant", verseRef:"Yusuf, 12:76", tip:"La racine alama donne aussi monde — savoir et monde sont liés." },
  { id:5, arabic:"قَلْب", transliteration:"Qalb", meaning:"Cœur", root:"قلب", frequency:132, verseNumber:200, verseArabic:"أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", verseFr:"C'est par le rappel d'Allah que les cœurs trouvent la quiétude", verseRef:"Ar-Ra'd, 13:28", tip:"Dans le Coran, le Qalb est le siège de l'intelligence et de la foi." },
  { id:6, arabic:"نُور", transliteration:"Nūr", meaning:"Lumière", root:"نور", frequency:43, verseNumber:354, verseArabic:"اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ", verseFr:"Allah est la lumière des cieux et de la terre", verseRef:"An-Nur, 24:35", tip:"Une sourate entière lui est dédiée — An-Nur." },
  { id:7, arabic:"صَبْر", transliteration:"Ṣabr", meaning:"Patience — Persévérance", root:"صبر", frequency:90, verseNumber:153, verseArabic:"إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", verseFr:"Certes, Allah est avec les endurants", verseRef:"Al-Baqara, 2:153", tip:"Sabr c'est tenir bon avec dignité et confiance." },
  { id:8, arabic:"هُدَى", transliteration:"Hudā", meaning:"Guidance — Direction", root:"هدي", frequency:316, verseNumber:2, verseArabic:"ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى", verseFr:"C'est le Livre, sans aucun doute, une guidance", verseRef:"Al-Baqara, 2:2", tip:"Le Coran se décrit lui-même comme Huda — une boussole." },
  { id:9, arabic:"حَقّ", transliteration:"Ḥaqq", meaning:"Vérité — Droit", root:"حقق", frequency:287, verseNumber:81, verseArabic:"وَقُلْ جَاءَ الْحَقُّ وَزَهَقَ الْبَاطِلُ", verseFr:"Dis : La vérité est venue et le faux a disparu", verseRef:"Al-Isra, 17:81", tip:"Al-Haqq est aussi l'un des 99 noms d'Allah." },
  { id:10, arabic:"شُكْر", transliteration:"Shukr", meaning:"Gratitude — Reconnaissance", root:"شكر", frequency:75, verseNumber:7, verseArabic:"لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", verseFr:"Si vous êtes reconnaissants, Je vous donnerai davantage", verseRef:"Ibrahim, 14:7", tip:"Différent de Hamd — Shukr c'est reconnaître un bienfait reçu." },
  { id:11, arabic:"إِيمَان", transliteration:"Īmān", meaning:"Foi — Croyance", root:"أمن", frequency:45, verseNumber:11, verseArabic:"وَمَن يُؤْمِن بِاللَّهِ يَهْدِ قَلْبَهُ", verseFr:"Quiconque croit en Allah, Il guidera son cœur", verseRef:"At-Taghabun, 64:11", tip:"De la même racine qu'Aman — la foi comme ancre intérieure." },
  { id:12, arabic:"جَنَّة", transliteration:"Janna", meaning:"Paradis — Jardin", root:"جنن", frequency:147, verseNumber:25, verseArabic:"أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ", verseFr:"Des jardins sous lesquels coulent les ruisseaux leur sont réservés", verseRef:"Al-Baqara, 2:25", tip:"Janna vient de ce qui est caché — un endroit inimaginable." },
  { id:13, arabic:"تَوْبَة", transliteration:"Tawba", meaning:"Repentir — Retour", root:"توب", frequency:87, verseNumber:222, verseArabic:"إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ", verseFr:"Certes, Allah aime ceux qui se repentent beaucoup", verseRef:"Al-Baqara, 2:222", tip:"Tawba = revenir. Revenir à Allah est toujours possible." },
  { id:14, arabic:"دُعَاء", transliteration:"Du'ā'", meaning:"Invocation — Prière", root:"دعو", frequency:212, verseNumber:60, verseArabic:"ادْعُونِي أَسْتَجِبْ لَكُمْ", verseFr:"Invoquez-Moi, Je vous répondrai", verseRef:"Ghafir, 40:60", tip:"Allah promet de répondre — Du'a est une conversation directe." },
  { id:15, arabic:"رَسُول", transliteration:"Rasūl", meaning:"Messager", root:"رسل", frequency:513, verseNumber:29, verseArabic:"مُّحَمَّدٌ رَّسُولُ اللَّهِ", verseFr:"Muhammad est le messager d'Allah", verseRef:"Al-Fath, 48:29", tip:"Rasul se distingue de Nabi — une distinction importante." },
  { id:16, arabic:"كِتَاب", transliteration:"Kitāb", meaning:"Livre — Écriture", root:"كتب", frequency:230, verseNumber:2, verseArabic:"ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ", verseFr:"C'est le Livre en lequel il n'y a aucun doute", verseRef:"Al-Baqara, 2:2", tip:"Kitab vient de kataba — écrire. Le Coran est l'écrit par excellence." },
  { id:17, arabic:"نَبِيّ", transliteration:"Nabī", meaning:"Prophète", root:"نبأ", frequency:75, verseNumber:40, verseArabic:"مَّا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِّن رِّجَالِكُمْ وَلَٰكِن رَّسُولَ اللَّهِ وَخَاتَمَ النَّبِيِّينَ", verseFr:"Muhammad n'est pas le père d'un de vos hommes, mais le Messager d'Allah et le sceau des prophètes", verseRef:"Al-Ahzab, 33:40", tip:"Nabi vient de naba — nouvelle. Le prophète apporte une nouvelle divine." },
  { id:18, arabic:"سَلَام", transliteration:"Salām", meaning:"Paix — Salut", root:"سلم", frequency:42, verseNumber:46, verseArabic:"سَلَامٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ", verseFr:"Paix, parole venant d'un Seigneur Très Miséricordieux", verseRef:"Ya-Sin, 36:58", tip:"As-Salam est l'un des 99 noms d'Allah — la Paix absolue." },
  { id:19, arabic:"صَلَاة", transliteration:"Ṣalāh", meaning:"Prière", root:"صلو", frequency:99, verseNumber:3, verseArabic:"وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ", verseFr:"Accomplissez la prière et acquittez la Zakat", verseRef:"Al-Baqara, 2:43", tip:"Salah vient de sila — connexion. La prière relie le croyant à Allah." },
  { id:20, arabic:"زَكَاة", transliteration:"Zakāh", meaning:"Aumône purificatrice", root:"زكو", frequency:32, verseNumber:3, verseArabic:"وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ", verseFr:"Accomplissez la prière et acquittez la Zakat", verseRef:"Al-Baqara, 2:43", tip:"Zakat vient de zaka — purifier. Donner purifie la richesse." },
  { id:21, arabic:"صِيَام", transliteration:"Ṣiyām", meaning:"Jeûne", root:"صوم", frequency:8, verseNumber:183, verseArabic:"يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ", verseFr:"Ô vous qui croyez, on vous a prescrit le jeûne", verseRef:"Al-Baqara, 2:183", tip:"Siyam = s'abstenir. Le jeûne est une abstention totale pour Allah." },
  { id:22, arabic:"حَجّ", transliteration:"Ḥajj", meaning:"Pèlerinage", root:"حجج", frequency:10, verseNumber:197, verseArabic:"الْحَجُّ أَشْهُرٌ مَّعْلُومَاتٌ", verseFr:"Le pèlerinage a lieu durant des mois bien connus", verseRef:"Al-Baqara, 2:197", tip:"Hajj vient de haja — se diriger vers. Un voyage vers Allah." },
  { id:23, arabic:"تَقْوَى", transliteration:"Taqwā", meaning:"Piété — Crainte révérencielle", root:"وقي", frequency:87, verseNumber:2, verseArabic:"هُدًى لِّلْمُتَّقِينَ", verseFr:"Une guidance pour les pieux", verseRef:"Al-Baqara, 2:2", tip:"Taqwa vient de waqa — protéger. La piété est un bouclier." },
  { id:24, arabic:"جِهَاد", transliteration:"Jihād", meaning:"Effort — Combat spirituel", root:"جهد", frequency:41, verseNumber:218, verseArabic:"وَالَّذِينَ آمَنُوا وَهَاجَرُوا وَجَاهَدُوا فِي سَبِيلِ اللَّهِ", verseFr:"Ceux qui ont cru, émigré et lutté dans le chemin d'Allah", verseRef:"Al-Baqara, 2:218", tip:"Jihad = effort intense. Le plus grand jihad est contre son propre ego." },
  { id:25, arabic:"أَمَانَة", transliteration:"Amāna", meaning:"Confiance — Dépôt", root:"أمن", frequency:6, verseNumber:72, verseArabic:"إِنَّا عَرَضْنَا الْأَمَانَةَ عَلَى السَّمَاوَاتِ وَالْأَرْضِ", verseFr:"Nous avons proposé le dépôt aux cieux et à la terre", verseRef:"Al-Ahzab, 33:72", tip:"L'Amana est la responsabilité humaine — un dépôt sacré." },
  { id:26, arabic:"عَدْل", transliteration:"'Adl", meaning:"Justice — Équité", root:"عدل", frequency:28, verseNumber:90, verseArabic:"إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ", verseFr:"Certes, Allah ordonne la justice et la bienfaisance", verseRef:"An-Nahl, 16:90", tip:"Al-Adl est l'un des 99 noms d'Allah — la Justice parfaite." },
  { id:27, arabic:"إِحْسَان", transliteration:"Iḥsān", meaning:"Excellence — Bienfaisance", root:"حسن", frequency:12, verseNumber:90, verseArabic:"إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ", verseFr:"Certes, Allah ordonne la justice et la bienfaisance", verseRef:"An-Nahl, 16:90", tip:"Ihsan = adorer Allah comme si tu Le voyais." },
  { id:28, arabic:"حِكْمَة", transliteration:"Ḥikma", meaning:"Sagesse", root:"حكم", frequency:20, verseNumber:269, verseArabic:"يُؤْتِي الْحِكْمَةَ مَن يَشَاءُ", verseFr:"Il accorde la sagesse à qui Il veut", verseRef:"Al-Baqara, 2:269", tip:"La hikma est au-delà du savoir — c'est mettre le savoir à sa juste place." },
  { id:29, arabic:"رَحِيم", transliteration:"Raḥīm", meaning:"Très Miséricordieux", root:"رحم", frequency:115, verseNumber:1, verseArabic:"بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", verseFr:"Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux", verseRef:"Al-Fatiha, 1:1", tip:"Rahim désigne la miséricorde spéciale d'Allah envers les croyants." },
  { id:30, arabic:"رَحْمَٰن", transliteration:"Raḥmān", meaning:"Tout Miséricordieux", root:"رحم", frequency:57, verseNumber:1, verseArabic:"بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", verseFr:"Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux", verseRef:"Al-Fatiha, 1:1", tip:"Rahman désigne la miséricorde universelle d'Allah envers toute la création." },

  // ========== NIVEAU 2 — Fatiha et courtes sourates ==========
  { id:31, arabic:"حَمْد", transliteration:"Ḥamd", meaning:"Louange — Éloge", root:"حمد", frequency:43, verseNumber:2, verseArabic:"الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", verseFr:"Louange à Allah, Seigneur des mondes", verseRef:"Al-Fatiha, 1:2", tip:"Hamd est une louange totale — pas seulement pour un bienfait." },
  { id:32, arabic:"عَالَم", transliteration:"'Ālam", meaning:"Monde — Univers", root:"علم", frequency:73, verseNumber:2, verseArabic:"الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", verseFr:"Louange à Allah, Seigneur des mondes", verseRef:"Al-Fatiha, 1:2", tip:"Alam vient de la même racine qu'ilm — le monde est un signe de connaissance." },
  { id:33, arabic:"مَلِك", transliteration:"Mālik", meaning:"Roi — Propriétaire", root:"ملك", frequency:53, verseNumber:4, verseArabic:"مَالِكِ يَوْمِ الدِّينِ", verseFr:"Maître du Jour de la Rétribution", verseRef:"Al-Fatiha, 1:4", tip:"Malik désigne la souveraineté absolue d'Allah sur le Jour du Jugement." },
  { id:34, arabic:"يَوْم", transliteration:"Yawm", meaning:"Jour", root:"يوم", frequency:405, verseNumber:4, verseArabic:"مَالِكِ يَوْمِ الدِّينِ", verseFr:"Maître du Jour de la Rétribution", verseRef:"Al-Fatiha, 1:4", tip:"Yawm ad-Din = le Jour de la Rétribution. Le mot yawm revient 405 fois." },
  { id:35, arabic:"دِين", transliteration:"Dīn", meaning:"Religion — Jugement — Mode de vie", root:"دين", frequency:92, verseNumber:4, verseArabic:"مَالِكِ يَوْمِ الدِّينِ", verseFr:"Maître du Jour de la Rétribution", verseRef:"Al-Fatiha, 1:4", tip:"Din a trois sens : religion, jugement et remboursement." },
  { id:36, arabic:"عِبَادَة", transliteration:"'Ibāda", meaning:"Adoration — Culte", root:"عبد", frequency:8, verseNumber:5, verseArabic:"إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", verseFr:"C'est Toi seul que nous adorons et c'est Toi seul dont nous implorons le secours", verseRef:"Al-Fatiha, 1:5", tip:"La ibada englobe tout acte fait pour Allah — travail, sourire, aide." },
  { id:37, arabic:"اِسْتِعَانَة", transliteration:"Isti'āna", meaning:"Implorer le secours", root:"عون", frequency:1, verseNumber:5, verseArabic:"إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", verseFr:"C'est Toi seul que nous adorons et c'est Toi seul dont nous implorons le secours", verseRef:"Al-Fatiha, 1:5", tip:"Nasta'in = nous demandons l'aide. Toujours au pluriel — on prie ensemble." },
  { id:38, arabic:"صِرَاط", transliteration:"Ṣirāṭ", meaning:"Chemin — Voie", root:"صرط", frequency:45, verseNumber:6, verseArabic:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", verseFr:"Guide-nous dans le droit chemin", verseRef:"Al-Fatiha, 1:6", tip:"On demande la guidance 17 fois par jour dans nos prières." },
  { id:39, arabic:"مُسْتَقِيم", transliteration:"Mustaqīm", meaning:"Droit — Direct", root:"قوم", frequency:36, verseNumber:6, verseArabic:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", verseFr:"Guide-nous dans le droit chemin", verseRef:"Al-Fatiha, 1:6", tip:"Mustaqim vient de qama — se lever. Le chemin droit est celui qui tient debout." },
  { id:40, arabic:"نِعْمَة", transliteration:"Ni'ma", meaning:"Bienfait — Grâce", root:"نعم", frequency:26, verseNumber:7, verseArabic:"صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ", verseFr:"Le chemin de ceux que Tu as comblés de bienfaits", verseRef:"Al-Fatiha, 1:7", tip:"Les bienfaits d'Allah sont innombrables — une sourate entière le rappelle." },
  { id:41, arabic:"أَحَد", transliteration:"Aḥad", meaning:"Un — Unique", root:"وحد", frequency:9, verseNumber:4780, verseArabic:"قُلْ هُوَ اللَّهُ أَحَدٌ", verseFr:"Dis : Il est Allah, l'Unique", verseRef:"Al-Ikhlas, 112:1", tip:"Ahad = unicité absolue. Différent de Wahid = un parmi d'autres." },
  { id:42, arabic:"صَمَد", transliteration:"Ṣamad", meaning:"L'Impénétrable — L'Absolu", root:"صمد", frequency:1, verseNumber:4781, verseArabic:"اللَّهُ الصَّمَدُ", verseFr:"Allah, l'Absolu", verseRef:"Al-Ikhlas, 112:2", tip:"Samad = celui dont tout le monde a besoin et qui n'a besoin de personne." },
  { id:43, arabic:"فَلَق", transliteration:"Falaq", meaning:"Aube — Fente", root:"فلق", frequency:1, verseNumber:4792, verseArabic:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", verseFr:"Dis : Je cherche refuge auprès du Seigneur de l'Aube", verseRef:"Al-Falaq, 113:1", tip:"Falaq = la fente de l'aube. Allah fend la nuit pour faire apparaître la lumière." },
  { id:44, arabic:"نَاس", transliteration:"Nās", meaning:"Gens — Humanité", root:"نوس", frequency:241, verseNumber:4797, verseArabic:"قُلْ أَعُوذُ بِرَبِّ النَّاسِ", verseFr:"Dis : Je cherche refuge auprès du Seigneur des hommes", verseRef:"An-Nas, 114:1", tip:"Nas = les gens. La dernière sourate protège des mauvaises influences humaines." },
  { id:45, arabic:"وَسْوَاس", transliteration:"Waswās", meaning:"Chuchotement — Tentation", root:"وسوس", frequency:2, verseNumber:4800, verseArabic:"مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", verseFr:"Du mal du chuchoteur sournois", verseRef:"An-Nas, 114:4", tip:"Waswas = le murmure de Satan. Il recule dès qu'on invoque Allah." },

  // ========== NIVEAU 3 — Mots de la vie spirituelle ==========
  { id:46, arabic:"ذِكْر", transliteration:"Dhikr", meaning:"Rappel — Invocation", root:"ذكر", frequency:292, verseNumber:152, verseArabic:"فَاذْكُرُونِي أَذْكُرْكُمْ", verseFr:"Rappelez-vous de Moi, Je me souviendrai de vous", verseRef:"Al-Baqara, 2:152", tip:"Le dhikr est la nourriture du cœur — plus on se rappelle d'Allah, plus on est vivant." },
  { id:47, arabic:"تَوَكُّل", transliteration:"Tawakkul", meaning:"Confiance en Allah", root:"وكل", frequency:5, verseNumber:159, verseArabic:"فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ", verseFr:"Quand tu te décides, place ta confiance en Allah", verseRef:"Aal Imran, 3:159", tip:"Tawakkul = agir puis s'en remettre à Allah. Pas la passivité." },
  { id:48, arabic:"إِخْلَاص", transliteration:"Ikhlāṣ", meaning:"Sincérité — Dévotion pure", root:"خلص", frequency:3, verseNumber:1, verseArabic:"قُلْ هُوَ اللَّهُ أَحَدٌ", verseFr:"Dis : Il est Allah, l'Unique", verseRef:"Al-Ikhlas, 112:1", tip:"Ikhlas = purifier son intention. La sourate Al-Ikhlas vaut un tiers du Coran." },
  { id:49, arabic:"خَشْيَة", transliteration:"Khashya", meaning:"Crainte révérencielle", root:"خشي", frequency:18, verseNumber:18, verseArabic:"إِنَّمَا يَخْشَى اللَّهَ مِنْ عِبَادِهِ الْعُلَمَاءُ", verseFr:"Parmi les serviteurs d'Allah, ce sont les savants qui Le craignent", verseRef:"Fatir, 35:28", tip:"Khashya est une crainte mêlée de respect et d'amour — pas de terreur." },
  { id:50, arabic:"تَضَرُّع", transliteration:"Taḍarru'", meaning:"Humilité — Supplication humble", root:"ضرع", frequency:5, verseNumber:55, verseArabic:"ادْعُوا رَبَّكُمْ تَضَرُّعًا وَخُفْيَةً", verseFr:"Invoquez votre Seigneur avec humilité et discrétion", verseRef:"Al-A'raf, 7:55", tip:"Tadharru = s'abaisser devant Allah avec le cœur." },
  { id:51, arabic:"يَقِين", transliteration:"Yaqīn", meaning:"Certitude absolue", root:"يقن", frequency:28, verseNumber:99, verseArabic:"وَاعْبُدْ رَبَّكَ حَتَّىٰ يَأْتِيَكَ الْيَقِينُ", verseFr:"Adore ton Seigneur jusqu'à ce que te vienne la certitude", verseRef:"Al-Hijr, 15:99", tip:"Yaqin = la mort selon les commentateurs. Adore jusqu'au dernier souffle." },
  { id:52, arabic:"صِدْق", transliteration:"Ṣidq", meaning:"Véracité — Sincérité", root:"صدق", frequency:155, verseNumber:119, verseArabic:"يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ وَكُونُوا مَعَ الصَّادِقِينَ", verseFr:"Ô croyants, craignez Allah et soyez avec les véridiques", verseRef:"At-Tawba, 9:119", tip:"Sidq englobe la vérité en parole, en acte et en intention." },
  { id:53, arabic:"حَيَاء", transliteration:"Ḥayā'", meaning:"Pudeur — Dignité", root:"حيي", frequency:2, verseNumber:25, verseArabic:"إِنَّ اللَّهَ لَا يَسْتَحْيِي أَن يَضْرِبَ مَثَلًا", verseFr:"Allah ne répugne pas à citer une parabole", verseRef:"Al-Baqara, 2:26", tip:"Haya = pudeur. Le Prophète ﷺ dit : la pudeur ne vient que du bien." },
  { id:54, arabic:"زُهْد", transliteration:"Zuhd", meaning:"Ascétisme — Détachement du monde", root:"زهد", frequency:2, verseNumber:20, verseArabic:"وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ", verseFr:"La vie d'ici-bas n'est que jouissance trompeuse", verseRef:"Aal Imran, 3:185", tip:"Zuhd ne signifie pas abandonner le monde, mais ne pas en être esclave." },
  { id:55, arabic:"وَرَع", transliteration:"Wara'", meaning:"Scrupule — Piété stricte", root:"ورع", frequency:1, verseNumber:32, verseArabic:"وَلَا تَقْرَبُوا الزِّنَىٰ إِنَّهُ كَانَ فَاحِشَةً وَسَاءَ سَبِيلًا", verseFr:"Ne vous approchez pas de la fornication", verseRef:"Al-Isra, 17:32", tip:"Wara = s'éloigner même du licite par précaution spirituelle." },

  // ========== NIVEAU 4 — Noms et attributs divins ==========
  { id:56, arabic:"خَالِق", transliteration:"Khāliq", meaning:"Créateur", root:"خلق", frequency:8, verseNumber:24, verseArabic:"هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ", verseFr:"C'est Allah le Créateur, le Réalisateur, le Façonneur", verseRef:"Al-Hashr, 59:24", tip:"Khaliq vient de khalaqa — créer de rien. Seul Allah peut créer ex nihilo." },
  { id:57, arabic:"عَزِيز", transliteration:"'Azīz", meaning:"Puissant — Tout-Puissant", root:"عزز", frequency:92, verseNumber:1, verseArabic:"الم اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", verseFr:"Allah ! Pas de divinité à part Lui, le Vivant, l'Éternel", verseRef:"Aal Imran, 3:2", tip:"Aziz = inaccessible dans sa grandeur. Rien ne peut Le vaincre." },
  { id:58, arabic:"حَكِيم", transliteration:"Ḥakīm", meaning:"Sage — Infiniment Sage", root:"حكم", frequency:97, verseNumber:129, verseArabic:"وَهُوَ الْعَزِيزُ الْحَكِيمُ", verseFr:"Il est le Puissant, le Sage", verseRef:"Al-Baqara, 2:129", tip:"Hakim = celui dont toutes les décisions sont parfaitement sages." },
  { id:59, arabic:"قَدِير", transliteration:"Qadīr", meaning:"Omnipotent — Capable de tout", root:"قدر", frequency:45, verseNumber:20, verseArabic:"وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", verseFr:"Allah est capable de toute chose", verseRef:"Al-Baqara, 2:20", tip:"Qadir vient de qudra — pouvoir absolu. Rien n'est impossible à Allah." },
  { id:60, arabic:"سَمِيع", transliteration:"Samī'", meaning:"Qui entend tout", root:"سمع", frequency:47, verseNumber:127, verseArabic:"إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ", verseFr:"Il est certes l'Audient, l'Omniscient", verseRef:"Al-Baqara, 2:127", tip:"Sami = Allah entend chaque souffle, chaque pensée, chaque pleur." },
  { id:61, arabic:"بَصِير", transliteration:"Baṣīr", meaning:"Qui voit tout", root:"بصر", frequency:42, verseNumber:110, verseArabic:"وَاللَّهُ بَصِيرٌ بِمَا تَعْمَلُونَ", verseFr:"Allah voit parfaitement ce que vous faites", verseRef:"Al-Baqara, 2:110", tip:"Basir = la vision divine pénètre les cœurs et les intentions cachées." },
  { id:62, arabic:"عَلِيم", transliteration:"'Alīm", meaning:"Omniscient — Qui sait tout", root:"علم", frequency:157, verseNumber:29, verseArabic:"إِنَّهُ عَلِيمٌ بِذَاتِ الصُّدُورِ", verseFr:"Il connaît parfaitement ce que renferment les poitrines", verseRef:"Al-Mulk, 67:13", tip:"Alim = savoir parfait et total, du plus grand au plus infime." },
  { id:63, arabic:"غَفُور", transliteration:"Ghafūr", meaning:"Très Pardonneur", root:"غفر", frequency:91, verseNumber:173, verseArabic:"فَمَنِ اضْطُرَّ غَيْرَ بَاغٍ وَلَا عَادٍ فَإِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ", verseFr:"Allah est Pardonneur et Miséricordieux", verseRef:"Al-Baqara, 2:173", tip:"Ghafur vient de ghafara — couvrir. Allah couvre les péchés comme un vêtement." },
  { id:64, arabic:"تَوَّاب", transliteration:"Tawwāb", meaning:"Celui qui accepte le repentir", root:"توب", frequency:11, verseNumber:37, verseArabic:"إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ", verseFr:"Il est Celui qui accepte le repentir, le Très Miséricordieux", verseRef:"Al-Baqara, 2:37", tip:"Tawwab = accepter le repentir encore et encore, sans jamais se lasser." },
  { id:65, arabic:"وَدُود", transliteration:"Wadūd", meaning:"Plein d'amour — Affectueux", root:"ودد", frequency:2, verseNumber:90, verseArabic:"وَهُوَ الْغَفُورُ الْوَدُودُ", verseFr:"Il est le Pardonneur, le Plein d'amour", verseRef:"Al-Buruj, 85:14", tip:"Wadud = amour actif. Allah n'aime pas passivement — Il agit par amour." },

  // ========== NIVEAU 5 — Le monde et la création ==========
  { id:66, arabic:"سَمَاء", transliteration:"Samā'", meaning:"Ciel", root:"سمو", frequency:190, verseNumber:22, verseArabic:"الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً", verseFr:"Celui qui a fait de la terre un lit et du ciel un édifice", verseRef:"Al-Baqara, 2:22", tip:"Sama vient de sama — être élevé. Le ciel est ce qui s'élève au-dessus de nous." },
  { id:67, arabic:"أَرْض", transliteration:"Arḍ", meaning:"Terre", root:"أرض", frequency:461, verseNumber:22, verseArabic:"الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا", verseFr:"Celui qui a fait de la terre un lit pour vous", verseRef:"Al-Baqara, 2:22", tip:"Ard = terre. Mentionné 461 fois — autant que sama (ciel). Symétrie parfaite." },
  { id:68, arabic:"مَاء", transliteration:"Mā'", meaning:"Eau", root:"موه", frequency:63, verseNumber:22, verseArabic:"وَأَنزَلَ مِنَ السَّمَاءِ مَاءً", verseFr:"Et Il a fait descendre du ciel de l'eau", verseRef:"Al-Baqara, 2:22", tip:"L'eau est mentionnée comme origine de toute vie dans le Coran." },
  { id:69, arabic:"شَمْس", transliteration:"Shams", meaning:"Soleil", root:"شمس", frequency:33, verseNumber:4609, verseArabic:"وَالشَّمْسِ وَضُحَاهَا", verseFr:"Par le soleil et son éclat matinal", verseRef:"Ash-Shams, 91:1", tip:"Une sourate entière s'appelle Ash-Shams — le Soleil." },
  { id:70, arabic:"قَمَر", transliteration:"Qamar", meaning:"Lune", root:"قمر", frequency:27, verseNumber:4613, verseArabic:"وَالْقَمَرِ إِذَا تَلَاهَا", verseFr:"Et par la lune quand elle la suit", verseRef:"Ash-Shams, 91:2", tip:"Une sourate entière s'appelle Al-Qamar — la Lune. Elle décrit la fin des temps." },
  { id:71, arabic:"نَجْم", transliteration:"Najm", meaning:"Étoile", root:"نجم", frequency:13, verseNumber:3524, verseArabic:"وَالنَّجْمِ إِذَا هَوَىٰ", verseFr:"Par l'étoile quand elle tombe", verseRef:"An-Najm, 53:1", tip:"Najm = étoile. La sourate An-Najm commence par un serment sur les étoiles." },
  { id:72, arabic:"بَحْر", transliteration:"Baḥr", meaning:"Mer — Océan", root:"بحر", frequency:41, verseNumber:32, verseArabic:"وَهُوَ الَّذِي سَخَّرَ الْبَحْرَ", verseFr:"C'est Lui qui a assujetti la mer", verseRef:"An-Nahl, 16:14", tip:"Bahr = mer. Mentionné avec les bénédictions de la navigation et de la nourriture." },
  { id:73, arabic:"نَهْر", transliteration:"Nahr", meaning:"Fleuve — Rivière", root:"نهر", frequency:54, verseNumber:25, verseArabic:"تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ", verseFr:"Sous lesquels coulent les ruisseaux", verseRef:"Al-Baqara, 2:25", tip:"Les rivières du Paradis coulent sans creuser leur lit — une eau miraculeuse." },
  { id:74, arabic:"جَبَل", transliteration:"Jabal", meaning:"Montagne", root:"جبل", frequency:39, verseNumber:15, verseArabic:"وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ بِكُمْ", verseFr:"Il a placé dans la terre des montagnes pour qu'elle ne vacille pas avec vous", verseRef:"An-Nahl, 16:15", tip:"Les montagnes sont des chevilles qui stabilisent la terre — un fait géologique." },
  { id:75, arabic:"رِيح", transliteration:"Rīḥ", meaning:"Vent", root:"روح", frequency:29, verseNumber:164, verseArabic:"وَتَصْرِيفِ الرِّيَاحِ", verseFr:"Et dans la direction des vents", verseRef:"Al-Baqara, 2:164", tip:"Le vent est un signe d'Allah — il transporte la pluie, pollinise les plantes." },

  // ========== NIVEAU 6 — L'être humain ==========
  { id:76, arabic:"إِنْسَان", transliteration:"Insān", meaning:"Être humain", root:"أنس", frequency:65, verseNumber:3, verseArabic:"خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ", verseFr:"Il a créé l'homme d'une adhérence", verseRef:"Al-Alaq, 96:2", tip:"Insan vient de uns — familiarité. L'homme est un être fait pour la relation." },
  { id:77, arabic:"عَقْل", transliteration:"'Aql", meaning:"Raison — Intelligence", root:"عقل", frequency:49, verseNumber:164, verseArabic:"لَآيَاتٍ لِّقَوْمٍ يَعْقِلُونَ", verseFr:"Il y a là des signes pour des gens qui raisonnent", verseRef:"Al-Baqara, 2:164", tip:"Aql vient de aqala — attacher. La raison attache l'homme au vrai." },
  { id:78, arabic:"رُوح", transliteration:"Rūḥ", meaning:"Âme — Esprit", root:"روح", frequency:21, verseNumber:85, verseArabic:"وَيَسْأَلُونَكَ عَنِ الرُّوحِ قُلِ الرُّوحُ مِنْ أَمْرِ رَبِّي", verseFr:"Ils t'interrogent sur l'âme. Dis : l'âme relève de l'ordre de mon Seigneur", verseRef:"Al-Isra, 17:85", tip:"Le Ruh reste un mystère que seul Allah connaît pleinement." },
  { id:79, arabic:"نَفْس", transliteration:"Nafs", meaning:"Âme — Moi — Personne", root:"نفس", frequency:295, verseNumber:286, verseArabic:"لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", verseFr:"Allah n'impose à aucune âme une charge supérieure à sa capacité", verseRef:"Al-Baqara, 2:286", tip:"Nafs a trois niveaux : l'ego primitif, l'âme qui blâme, et l'âme apaisée." },
  { id:80, arabic:"جَسَد", transliteration:"Jasad", meaning:"Corps", root:"جسد", frequency:2, verseNumber:148, verseArabic:"فَأَخْرَجَ لَهُمْ عِجْلًا جَسَدًا لَّهُ خُوَارٌ", verseFr:"Il leur sortit un veau, un corps qui meuglait", verseRef:"Ta-Ha, 20:88", tip:"Jasad = corps physique. L'enveloppe temporaire de l'âme." },
  { id:81, arabic:"لِسَان", transliteration:"Lisān", meaning:"Langue — Langage", root:"لسن", frequency:25, verseNumber:103, verseArabic:"لِّسَانُ الَّذِي يُلْحِدُونَ إِلَيْهِ أَعْجَمِيٌّ", verseFr:"La langue de celui vers lequel ils l'imputent est étrangère", verseRef:"An-Nahl, 16:103", tip:"Le Coran est un miracle linguistique arabe — la langue est sacrée." },
  { id:82, arabic:"عَيْن", transliteration:"'Ayn", meaning:"Œil — Source", root:"عين", frequency:56, verseNumber:13, verseArabic:"تَجْرِي بِأَعْيُنِنَا", verseFr:"Naviguant sous nos yeux", verseRef:"Al-Qamar, 54:14", tip:"Ayn a deux sens : l'œil et la source d'eau — deux sources de vie." },
  { id:83, arabic:"يَد", transliteration:"Yad", meaning:"Main", root:"يدي", frequency:120, verseNumber:195, verseArabic:"وَلَا تُلْقُوا بِأَيْدِيكُمْ إِلَى التَّهْلُكَةِ", verseFr:"Ne vous jetez pas de vos propres mains dans la perdition", verseRef:"Al-Baqara, 2:195", tip:"La main symbolise l'action et la responsabilité dans le Coran." },
  { id:84, arabic:"وَجْه", transliteration:"Wajh", meaning:"Visage — Face", root:"وجه", frequency:72, verseNumber:115, verseArabic:"فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ", verseFr:"Où que vous vous tourniez, là est la Face d'Allah", verseRef:"Al-Baqara, 2:115", tip:"La Face d'Allah = sa présence et sa vigilance partout." },
  { id:85, arabic:"وَلَد", transliteration:"Walad", meaning:"Enfant — Fils", root:"ولد", frequency:44, verseNumber:3, verseArabic:"لَمْ يَلِدْ وَلَمْ يُولَدْ", verseFr:"Il n'a pas engendré et n'a pas été engendré", verseRef:"Al-Ikhlas, 112:3", tip:"Allah n'est pas père et n'a pas de fils — l'unicité divine absolue." },

  // ========== NIVEAU 7 — La vie et la mort ==========
  { id:86, arabic:"حَيَاة", transliteration:"Ḥayāh", meaning:"Vie", root:"حيي", frequency:76, verseNumber:28, verseArabic:"كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنتُمْ أَمْوَاتًا فَأَحْيَاكُمْ", verseFr:"Comment pouvez-vous renier Allah, alors que vous étiez morts et qu'Il vous a donné la vie", verseRef:"Al-Baqara, 2:28", tip:"La vie est un don d'Allah — on était morts avant de naître." },
  { id:87, arabic:"مَوْت", transliteration:"Mawt", meaning:"Mort", root:"موت", frequency:68, verseNumber:2, verseArabic:"الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ", verseFr:"Celui qui a créé la mort et la vie", verseRef:"Al-Mulk, 67:2", tip:"La mort est une création d'Allah — elle a un but : tester qui fait le meilleur bien." },
  { id:88, arabic:"بَعْث", transliteration:"Ba'th", meaning:"Résurrection — Envoi", root:"بعث", frequency:40, verseNumber:56, verseArabic:"ثُمَّ بَعَثْنَاكُم مِّن بَعْدِ مَوْتِكُمْ", verseFr:"Puis Nous vous avons ressuscités après votre mort", verseRef:"Al-Baqara, 2:56", tip:"Ba'tha = envoyer puis ressusciter. La mort n'est qu'un sommeil." },
  { id:89, arabic:"قِيَامَة", transliteration:"Qiyāma", meaning:"Résurrection — Jour du Jugement", root:"قوم", frequency:70, verseNumber:1, verseArabic:"لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ", verseFr:"Je jure par le Jour de la Résurrection", verseRef:"Al-Qiyama, 75:1", tip:"Qiyama vient de qama — se lever. Toute la création se lèvera pour le jugement." },
  { id:90, arabic:"حِسَاب", transliteration:"Ḥisāb", meaning:"Jugement — Compte rendu", root:"حسب", frequency:109, verseNumber:202, verseArabic:"أُولَٰئِكَ لَهُمْ نَصِيبٌ مِّمَّا كَسَبُوا وَاللَّهُ سَرِيعُ الْحِسَابِ", verseFr:"Allah est prompt dans le jugement", verseRef:"Al-Baqara, 2:202", tip:"Hisab = le compte. Chaque acte, même imperceptible, sera compté." },
  { id:91, arabic:"مِيزَان", transliteration:"Mīzān", meaning:"Balance — Équilibre", root:"وزن", frequency:15, verseNumber:7, verseArabic:"وَالسَّمَاءَ رَفَعَهَا وَوَضَعَ الْمِيزَانَ", verseFr:"Il a élevé le ciel et établi la balance", verseRef:"Ar-Rahman, 55:7", tip:"La balance divine pèse les actes avec une précision infinie." },
  { id:92, arabic:"صِرَاط", transliteration:"Ṣirāṭ", meaning:"Pont — Chemin étroit", root:"صرط", frequency:45, verseNumber:6, verseArabic:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", verseFr:"Guide-nous dans le droit chemin", verseRef:"Al-Fatiha, 1:6", tip:"Le pont sur l'enfer que chacun doit traverser — plus fin qu'un cheveu." },
  { id:93, arabic:"نَار", transliteration:"Nār", meaning:"Feu — Enfer", root:"نور", frequency:145, verseNumber:24, verseArabic:"فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ", verseFr:"Craignez le Feu dont le combustible est les hommes et les pierres", verseRef:"Al-Baqara, 2:24", tip:"Nar et Nur ont la même racine — le feu peut détruire ou éclairer selon l'usage." },
  { id:94, arabic:"عَذَاب", transliteration:"'Adhāb", meaning:"Châtiment — Tourment", root:"عذب", frequency:322, verseNumber:10, verseArabic:"إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ", verseFr:"Allah ne manque pas à Sa promesse", verseRef:"Aal Imran, 3:9", tip:"Adhab désigne aussi bien le châtiment terrestre que celui de l'au-delà." },
  { id:95, arabic:"ثَوَاب", transliteration:"Thawāb", meaning:"Récompense divine", root:"ثوب", frequency:35, verseNumber:195, verseArabic:"فَآتَاهُمُ اللَّهُ ثَوَابَ الدُّنْيَا وَحُسْنَ ثَوَابِ الْآخِرَةِ", verseFr:"Allah leur donna la récompense de ce monde et la meilleure récompense de l'au-delà", verseRef:"Aal Imran, 3:148", tip:"Thawab = récompense qui revient comme un boomerang — tout bien revient." },

  // ========== NIVEAU 8 — Les prophètes ==========
  { id:96, arabic:"آدَم", transliteration:"Ādam", meaning:"Adam", root:"أدم", frequency:25, verseNumber:31, verseArabic:"وَعَلَّمَ آدَمَ الْأَسْمَاءَ كُلَّهَا", verseFr:"Et Il apprit à Adam tous les noms", verseRef:"Al-Baqara, 2:31", tip:"Adam fut honoré par la connaissance des noms — la langue est un don divin." },
  { id:97, arabic:"إِبْرَاهِيم", transliteration:"Ibrāhīm", meaning:"Abraham", root:"عبري", frequency:69, verseNumber:124, verseArabic:"وَإِذِ ابْتَلَىٰ إِبْرَاهِيمَ رَبُّهُ بِكَلِمَاتٍ", verseFr:"Quand le Seigneur éprouva Abraham par des commandements", verseRef:"Al-Baqara, 2:124", tip:"Ibrahim est le père des prophètes — il reconstruisit la Kaaba avec son fils." },
  { id:98, arabic:"مُوسَى", transliteration:"Mūsā", meaning:"Moïse", root:"عبري", frequency:136, verseNumber:49, verseArabic:"وَإِذْ نَجَّيْنَاكُم مِّنْ آلِ فِرْعَوْنَ", verseFr:"Quand Nous vous avons sauvés des gens de Pharaon", verseRef:"Al-Baqara, 2:49", tip:"Musa est le prophète le plus mentionné dans le Coran — 136 fois." },
  { id:99, arabic:"عِيسَى", transliteration:"'Īsā", meaning:"Jésus", root:"عبري", frequency:25, verseNumber:87, verseArabic:"وَآتَيْنَا عِيسَى ابْنَ مَرْيَمَ الْبَيِّنَاتِ", verseFr:"Nous avons donné à Jésus fils de Marie les preuves évidentes", verseRef:"Al-Baqara, 2:87", tip:"Isa est un prophète honoré — il reviendra à la fin des temps selon l'islam." },
  { id:100, arabic:"مُحَمَّد", transliteration:"Muḥammad", meaning:"Le Très Loué", root:"حمد", frequency:4, verseNumber:144, verseArabic:"مَّا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِّن رِّجَالِكُمْ", verseFr:"Muhammad n'est le père d'aucun de vos hommes", verseRef:"Al-Ahzab, 33:40", tip:"Muhammad = le très loué. Son nom vient de la même racine que hamd." },

  // ========== NIVEAU 9 — Les actions ==========
  { id:101, arabic:"عَمَل", transliteration:"'Amal", meaning:"Action — Œuvre", root:"عمل", frequency:359, verseNumber:7, verseArabic:"فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", verseFr:"Celui qui aura fait le poids d'un atome de bien le verra", verseRef:"Az-Zalzala, 99:7", tip:"Le plus petit acte est enregistré — rien n'est perdu devant Allah." },
  { id:102, arabic:"قَوْل", transliteration:"Qawl", meaning:"Parole — Dire", root:"قول", frequency:529, verseNumber:30, verseArabic:"قَوْلًا سَدِيدًا", verseFr:"Une parole droite", verseRef:"Al-Ahzab, 33:70", tip:"La parole est un acte — chaque mot est enregistré et aura un poids." },
  { id:103, arabic:"نِيَّة", transliteration:"Niyya", meaning:"Intention", root:"نوي", frequency:1, verseNumber:5, verseArabic:"إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", verseFr:"C'est Toi seul que nous adorons", verseRef:"Al-Fatiha, 1:5", tip:"La niyya est le fondement de tout acte — les actes valent par leurs intentions." },
  { id:104, arabic:"هِجْرَة", transliteration:"Hijra", meaning:"Migration — Exil pour Allah", root:"هجر", frequency:10, verseNumber:218, verseArabic:"إِنَّ الَّذِينَ آمَنُوا وَالَّذِينَ هَاجَرُوا", verseFr:"Ceux qui ont cru et ceux qui ont émigré", verseRef:"Al-Baqara, 2:218", tip:"La hijra du Prophète ﷺ est si importante que le calendrier islamique en part." },
  { id:105, arabic:"جِهَاد", transliteration:"Jihād", meaning:"Effort — Lutte", root:"جهد", frequency:41, verseNumber:218, verseArabic:"وَجَاهَدُوا فِي سَبِيلِ اللَّهِ", verseFr:"Et lutté dans le chemin d'Allah", verseRef:"Al-Baqara, 2:218", tip:"Le plus grand jihad est la lutte contre son propre ego." },
  { id:106, arabic:"إِنْفَاق", transliteration:"Infāq", meaning:"Dépenser — Donner", root:"نفق", frequency:25, verseNumber:3, verseArabic:"وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ", verseFr:"Et ils dépensent de ce que Nous leur avons accordé", verseRef:"Al-Baqara, 2:3", tip:"Infaq = donner de ce qu'on a reçu. Tout bien appartient à Allah." },
  { id:107, arabic:"تَسْبِيح", transliteration:"Tasbīḥ", meaning:"Glorification divine", root:"سبح", frequency:92, verseNumber:1, verseArabic:"سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ", verseFr:"Ce qui est dans les cieux et sur la terre glorifie Allah", verseRef:"Al-Hadid, 57:1", tip:"Tout dans l'univers glorifie Allah — même les pierres et les arbres." },
  { id:108, arabic:"اِسْتِغْفَار", transliteration:"Istighfār", meaning:"Demande de pardon", root:"غفر", frequency:36, verseNumber:3, verseArabic:"وَاسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ", verseFr:"Demandez pardon à votre Seigneur puis revenez à Lui", verseRef:"Hud, 11:3", tip:"Le Prophète ﷺ demandait pardon 70 fois par jour malgré son rang." },
  { id:109, arabic:"صَدَقَة", transliteration:"Ṣadaqa", meaning:"Aumône — Don volontaire", root:"صدق", frequency:12, verseNumber:264, verseArabic:"يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تُبْطِلُوا صَدَقَاتِكُم", verseFr:"Ô croyants, n'annulez pas vos aumônes", verseRef:"Al-Baqara, 2:264", tip:"Sadaqa vient de sidq — la sincérité. Donner est preuve de sincérité." },
  { id:110, arabic:"وَصِيَّة", transliteration:"Waṣiyya", meaning:"Testament — Recommandation", root:"وصي", frequency:9, verseNumber:180, verseArabic:"كُتِبَ عَلَيْكُمْ إِذَا حَضَرَ أَحَدَكُمُ الْمَوْتُ إِن تَرَكَ خَيْرًا الْوَصِيَّةُ", verseFr:"On vous a prescrit, quand la mort s'approche de l'un d'entre vous, de faire un testament", verseRef:"Al-Baqara, 2:180", tip:"La wasiyya est une obligation — préparer sa mort est un acte de sagesse." },

  // ========== NIVEAU 10 — Relations humaines ==========
  { id:111, arabic:"أَهْل", transliteration:"Ahl", meaning:"Famille — Gens", root:"أهل", frequency:127, verseNumber:132, verseArabic:"وَوَصَّىٰ بِهَا إِبْرَاهِيمُ بَنِيهِ وَيَعْقُوبُ يَا بَنِيَّ إِنَّ اللَّهَ اصْطَفَىٰ لَكُمُ الدِّينَ", verseFr:"Abraham en fit la recommandation à ses fils", verseRef:"Al-Baqara, 2:132", tip:"Ahl = ceux qui appartiennent à un lieu ou une famille. La famille est sacrée." },
  { id:112, arabic:"وَالِد", transliteration:"Wālid", meaning:"Parent — Père", root:"ولد", frequency:20, verseNumber:83, verseArabic:"وَبِالْوَالِدَيْنِ إِحْسَانًا", verseFr:"Et envers les père et mère, de la bonté", verseRef:"Al-Baqara, 2:83", tip:"Les parents sont mentionnés juste après Allah dans de nombreux versets." },
  { id:113, arabic:"أَخ", transliteration:"Akh", meaning:"Frère", root:"أخو", frequency:96, verseNumber:220, verseArabic:"وَإِن تُخَالِطُوهُمْ فَإِخْوَانُكُمْ", verseFr:"Si vous vous mêlez à eux, ils sont vos frères", verseRef:"Al-Baqara, 2:220", tip:"La fraternité islamique dépasse le sang — tous les croyants sont frères." },
  { id:114, arabic:"جَار", transliteration:"Jār", meaning:"Voisin", root:"جور", frequency:6, verseNumber:36, verseArabic:"وَالْجَارِ ذِي الْقُرْبَىٰ وَالْجَارِ الْجُنُبِ", verseFr:"Le voisin proche et le voisin lointain", verseRef:"An-Nisa, 4:36", tip:"Le Prophète ﷺ a tant insisté sur les droits du voisin qu'il croyait qu'il hériterait." },
  { id:115, arabic:"يَتِيم", transliteration:"Yatīm", meaning:"Orphelin", root:"يتم", frequency:22, verseNumber:83, verseArabic:"وَالْيَتَامَىٰ وَالْمَسَاكِينِ", verseFr:"Les orphelins et les pauvres", verseRef:"Al-Baqara, 2:83", tip:"Prendre soin des orphelins est une des grandes vertus dans le Coran." },
  { id:116, arabic:"مِسْكِين", transliteration:"Miskīn", meaning:"Pauvre — Démuni", root:"سكن", frequency:23, verseNumber:177, verseArabic:"وَآتَى الْمَالَ عَلَىٰ حُبِّهِ ذَوِي الْقُرْبَىٰ وَالْيَتَامَىٰ وَالْمَسَاكِينَ", verseFr:"Et donner de l'argent, malgré son amour pour lui, aux proches, aux orphelins, aux nécessiteux", verseRef:"Al-Baqara, 2:177", tip:"Miskin vient de sukun — immobilité. Celui qui est coincé dans la pauvreté." },
  { id:117, arabic:"ضَيْف", transliteration:"Ḍayf", meaning:"Invité — Hôte", root:"ضيف", frequency:4, verseNumber:24, verseArabic:"هَلْ أَتَاكَ حَدِيثُ ضَيْفِ إِبْرَاهِيمَ الْمُكْرَمِينَ", verseFr:"T'est-il parvenu le récit des hôtes honorés d'Abraham", verseRef:"Adh-Dhariyat, 51:24", tip:"Abraham honora ses invités angéliques — l'hospitalité est un pilier islamique." },
  { id:118, arabic:"شَهِيد", transliteration:"Shahīd", meaning:"Martyr — Témoin", root:"شهد", frequency:53, verseNumber:154, verseArabic:"وَلَا تَقُولُوا لِمَن يُقْتَلُ فِي سَبِيلِ اللَّهِ أَمْوَاتٌ", verseFr:"Ne dites pas de ceux qui sont tués dans le chemin d'Allah qu'ils sont morts", verseRef:"Al-Baqara, 2:154", tip:"Shahid = témoin. Le martyr témoigne de sa foi par sa vie." },
  { id:119, arabic:"عَالِم", transliteration:"'Ālim", meaning:"Savant — Érudit", root:"علم", frequency:13, verseNumber:11, verseArabic:"يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ", verseFr:"Allah élève ceux d'entre vous qui ont cru et ceux à qui le savoir a été donné", verseRef:"Al-Mujadala, 58:11", tip:"Les savants héritent des prophètes — la connaissance élève le rang." },
  { id:120, arabic:"وَلِيّ", transliteration:"Walī", meaning:"Protecteur — Ami intime d'Allah", root:"ولي", frequency:124, verseNumber:257, verseArabic:"اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا", verseFr:"Allah est le Protecteur de ceux qui croient", verseRef:"Al-Baqara, 2:257", tip:"Wali = ami proche. Al-Wali est un des 99 noms d'Allah — le Protecteur." },

  // ========== NIVEAU 11 — Concepts spirituels avancés ==========
  { id:121, arabic:"بَاطِل", transliteration:"Bāṭil", meaning:"Faux — Vain — Nul", root:"بطل", frequency:36, verseNumber:42, verseArabic:"وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ", verseFr:"Ne confondez pas la vérité avec le mensonge", verseRef:"Al-Baqara, 2:42", tip:"Batil = ce qui disparaît. La vérité reste — le faux s'évanouit toujours." },
  { id:122, arabic:"غَيْب", transliteration:"Ghayb", meaning:"Invisible — Non-manifesté", root:"غيب", frequency:49, verseNumber:3, verseArabic:"الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ", verseFr:"Ceux qui croient à l'invisible", verseRef:"Al-Baqara, 2:3", tip:"Le Ghayb englobe ce que seul Allah connaît — l'âme, la mort, le Paradis." },
  { id:123, arabic:"شَهَادَة", transliteration:"Shahāda", meaning:"Témoignage — Visible", root:"شهد", frequency:20, verseNumber:73, verseArabic:"عَالِمُ الْغَيْبِ وَالشَّهَادَةِ", verseFr:"Connaisseur du visible et de l'invisible", verseRef:"Al-An'am, 6:73", tip:"Shahada = le visible, ce qu'on peut témoigner. L'opposé du Ghayb." },
  { id:124, arabic:"آيَة", transliteration:"Āya", meaning:"Signe — Verset", root:"أيي", frequency:382, verseNumber:1, verseArabic:"تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ", verseFr:"Voilà les versets du Livre explicite", verseRef:"Yusuf, 12:1", tip:"Aya = signe et verset. Chaque chose dans l'univers est un verset d'Allah." },
  { id:125, arabic:"سُورَة", transliteration:"Sūra", meaning:"Chapitre du Coran", root:"سور", frequency:9, verseNumber:23, verseArabic:"فَأْتُوا بِسُورَةٍ مِّن مِّثْلِهِ", verseFr:"Apportez donc une sourate semblable", verseRef:"Al-Baqara, 2:23", tip:"Sura vient de sur — mur d'enceinte. Chaque sourate est un espace protégé." },
  { id:126, arabic:"وَحْي", transliteration:"Waḥy", meaning:"Révélation divine", root:"وحي", frequency:78, verseNumber:51, verseArabic:"وَمَا كَانَ لِبَشَرٍ أَن يُكَلِّمَهُ اللَّهُ إِلَّا وَحْيًا", verseFr:"Il n'appartient pas à un être humain qu'Allah lui parle autrement que par révélation", verseRef:"Ash-Shura, 42:51", tip:"Le Wahy est la communication divine — différente de toute communication humaine." },
  { id:127, arabic:"تَنْزِيل", transliteration:"Tanzīl", meaning:"Descente — Révélation progressive", root:"نزل", frequency:21, verseNumber:192, verseArabic:"وَإِنَّهُ لَتَنزِيلُ رَبِّ الْعَالَمِينَ", verseFr:"C'est bien une révélation du Seigneur des mondes", verseRef:"Ash-Shu'ara, 26:192", tip:"Le Coran fut révélé en 23 ans — une sagesse pédagogique divine." },
  { id:128, arabic:"بُرْهَان", transliteration:"Burhān", meaning:"Preuve — Argument décisif", root:"برهن", frequency:8, verseNumber:174, verseArabic:"قَدْ جَاءَكُم بُرْهَانٌ مِّن رَّبِّكُمْ", verseFr:"Une preuve décisive vous est venue de votre Seigneur", verseRef:"An-Nisa, 4:174", tip:"Burhan = preuve irréfutable. Le Coran est lui-même le plus grand burhan." },
  { id:129, arabic:"مُعْجِزَة", transliteration:"Mu'jiza", meaning:"Miracle", root:"عجز", frequency:3, verseNumber:23, verseArabic:"فَأْتُوا بِسُورَةٍ مِّن مِّثْلِهِ", verseFr:"Apportez donc une sourate semblable", verseRef:"Al-Baqara, 2:23", tip:"Mu'jiza = ce qui rend impuissant. Le Coran défie l'humanité depuis 14 siècles." },
  { id:130, arabic:"فِطْرَة", transliteration:"Fiṭra", meaning:"Nature primordiale — Disposition naturelle", root:"فطر", frequency:3, verseNumber:30, verseArabic:"فِطْرَتَ اللَّهِ الَّتِي فَطَرَ النَّاسَ عَلَيْهَا", verseFr:"La nature originelle selon laquelle Allah a créé les hommes", verseRef:"Ar-Rum, 30:30", tip:"La fitra = reconnaître Allah est inné. L'incroyance est une déviation." },

  // ========== NIVEAU 12 — Éthique et caractère ==========
  { id:131, arabic:"كَرَم", transliteration:"Karam", meaning:"Générosité — Noblesse", root:"كرم", frequency:8, verseNumber:3, verseArabic:"اقْرَأْ وَرَبُّكَ الْأَكْرَمُ", verseFr:"Lis, et ton Seigneur est le Très Généreux", verseRef:"Al-Alaq, 96:3", tip:"Allah est Al-Akram — le plus généreux. La générosité est un attribut divin." },
  { id:132, arabic:"وَفَاء", transliteration:"Wafā'", meaning:"Fidélité — Loyauté", root:"وفي", frequency:12, verseNumber:177, verseArabic:"وَالْمُوفُونَ بِعَهْدِهِمْ إِذَا عَاهَدُوا", verseFr:"Ceux qui tiennent leurs engagements quand ils s'engagent", verseRef:"Al-Baqara, 2:177", tip:"La wafa est le ciment des relations — tenir sa parole est signe de foi." },
  { id:133, arabic:"عَفْو", transliteration:"'Afw", meaning:"Pardon — Effacement", root:"عفو", frequency:35, verseNumber:199, verseArabic:"خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ", verseFr:"Accepte le pardon, ordonne le bien", verseRef:"Al-A'raf, 7:199", tip:"Al-Afuw = effacer complètement. Allah efface les péchés comme s'ils n'avaient jamais existé." },
  { id:134, arabic:"حِلْم", transliteration:"Ḥilm", meaning:"Douceur — Mansuétude", root:"حلم", frequency:11, verseNumber:101, verseArabic:"إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ أَوَّاهٌ مُّنِيبٌ", verseFr:"Abraham était doux, compatissant et repentant", verseRef:"Hud, 11:75", tip:"Hilm = retenir sa colère par sagesse. Allah est Al-Halim — le Très Doux." },
  { id:135, arabic:"شَجَاعَة", transliteration:"Shajā'a", meaning:"Courage — Bravoure", root:"شجع", frequency:1, verseNumber:35, verseArabic:"وَلَا تَهِنُوا وَلَا تَحْزَنُوا", verseFr:"Ne faiblissez pas et ne vous attristez pas", verseRef:"Aal Imran, 3:139", tip:"Le vrai courage est de dire la vérité face au pouvoir — un acte coranique." },
  { id:136, arabic:"صَبُور", transliteration:"Ṣabūr", meaning:"Très Patient", root:"صبر", frequency:1, verseNumber:400, verseArabic:"إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", verseFr:"Allah est avec les patients", verseRef:"Al-Baqara, 2:153", tip:"As-Sabur est l'un des 99 noms d'Allah — une patience infinie et parfaite." },
  { id:137, arabic:"تَوَاضُع", transliteration:"Tawāḍu'", meaning:"Humilité", root:"وضع", frequency:3, verseNumber:63, verseArabic:"وَعِبَادُ الرَّحْمَٰنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا", verseFr:"Les serviteurs du Tout-Miséricordieux sont ceux qui marchent humblement sur la terre", verseRef:"Al-Furqan, 25:63", tip:"Marcher avec humilité = ne pas se pavaner. L'humilité est visible dans la démarche." },
  { id:138, arabic:"كِبْر", transliteration:"Kibr", meaning:"Orgueil — Arrogance", root:"كبر", frequency:10, verseNumber:206, verseArabic:"وَإِذَا قِيلَ لَهُ اتَّقِ اللَّهَ أَخَذَتْهُ الْعِزَّةُ بِالْإِثْمِ", verseFr:"Quand on lui dit : crains Allah, l'orgueil le saisit et le pousse au péché", verseRef:"Al-Baqara, 2:206", tip:"L'orgueil est le premier péché — Iblis refusa de se prosterner par orgueil." },
  { id:139, arabic:"حَسَد", transliteration:"Ḥasad", meaning:"Jalousie — Envie", root:"حسد", frequency:3, verseNumber:4795, verseArabic:"وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ", verseFr:"Et du mal de l'envieux quand il envie", verseRef:"Al-Falaq, 113:5", tip:"La jalousie brûle les bonnes œuvres comme le feu brûle le bois sec." },
  { id:140, arabic:"رِيَاء", transliteration:"Riyā'", meaning:"Hypocrisie — Ostentation", root:"رأي", frequency:1, verseNumber:264, verseArabic:"لَا تُبْطِلُوا صَدَقَاتِكُم بِالْمَنِّ وَالْأَذَىٰ", verseFr:"N'annulez pas vos aumônes par des reproches et des offenses", verseRef:"Al-Baqara, 2:264", tip:"Le Riya = faire pour être vu. C'est le shirk caché — le plus dangereux." },

  // ========== NIVEAU 13 — Les temps et l'espace ==========
  { id:141, arabic:"لَيْل", transliteration:"Layl", meaning:"Nuit", root:"ليل", frequency:92, verseNumber:1, verseArabic:"وَاللَّيْلِ إِذَا يَغْشَىٰ", verseFr:"Par la nuit quand elle enveloppe", verseRef:"Al-Layl, 92:1", tip:"La nuit est le moment privilégié de la prière — Allah descend au tiers de la nuit." },
  { id:142, arabic:"نَهَار", transliteration:"Nahār", meaning:"Jour — Journée", root:"نهر", frequency:57, verseNumber:2, verseArabic:"وَالنَّهَارِ إِذَا تَجَلَّىٰ", verseFr:"Et par le jour quand il s'illumine", verseRef:"Al-Layl, 92:2", tip:"Layl et Nahar alternent comme des signes d'Allah — 92 fois chacun dans le Coran." },
  { id:143, arabic:"فَجْر", transliteration:"Fajr", meaning:"Aube — Aurore", root:"فجر", frequency:6, verseNumber:1, verseArabic:"وَالْفَجْرِ", verseFr:"Par l'aurore", verseRef:"Al-Fajr, 89:1", tip:"La prière du Fajr est la plus méritoire — récitée devant les anges." },
  { id:144, arabic:"عَصْر", transliteration:"'Aṣr", meaning:"Temps — Après-midi", root:"عصر", frequency:3, verseNumber:1, verseArabic:"وَالْعَصْرِ", verseFr:"Par le Temps", verseRef:"Al-Asr, 103:1", tip:"La sourate Al-Asr résume toute la religion en 3 versets selon Imam Shafi'i." },
  { id:145, arabic:"أَبَد", transliteration:"Abad", meaning:"Éternité — Toujours", root:"أبد", frequency:28, verseNumber:257, verseArabic:"هُمْ فِيهَا خَالِدُونَ", verseFr:"Ils y demeureront éternellement", verseRef:"Al-Baqara, 2:257", tip:"Abad = l'éternité future. L'au-delà n'a pas de fin — contrairement à ce monde." },
  { id:146, arabic:"آخِرَة", transliteration:"Ākhira", meaning:"Au-delà — Vie future", root:"أخر", frequency:115, verseNumber:4, verseArabic:"وَبِالْآخِرَةِ هُمْ يُوقِنُونَ", verseFr:"Et ils ont la certitude de l'au-delà", verseRef:"Al-Baqara, 2:4", tip:"L'Akhira = la vraie vie. Ce monde n'est qu'un passage." },
  { id:147, arabic:"دُنْيَا", transliteration:"Dunyā", meaning:"Monde d'ici-bas", root:"دنو", frequency:115, verseNumber:212, verseArabic:"زُيِّنَ لِلَّذِينَ كَفَرُوا الْحَيَاةُ الدُّنْيَا", verseFr:"La vie d'ici-bas a été embellie pour ceux qui ne croient pas", verseRef:"Al-Baqara, 2:212", tip:"Dunya vient de dana — être proche et bas. Ce monde est proche mais bas." },
  { id:148, arabic:"زَمَان", transliteration:"Zamān", meaning:"Temps — Époque", root:"زمن", frequency:3, verseNumber:1, verseArabic:"وَالْعَصْرِ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ", verseFr:"Par le Temps, l'être humain est en perdition", verseRef:"Al-Asr, 103:1-2", tip:"Le temps est un capital — le gaspiller est une perte certaine." },
  { id:149, arabic:"مَكَان", transliteration:"Makān", meaning:"Lieu — Endroit", root:"كون", frequency:23, verseNumber:115, verseArabic:"فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ", verseFr:"Où que vous vous tourniez, là est la Face d'Allah", verseRef:"Al-Baqara, 2:115", tip:"Allah n'est pas dans un lieu — Il est partout, omnipotent." },
  { id:150, arabic:"مَسْجِد", transliteration:"Masjid", meaning:"Mosquée — Lieu de prosternation", root:"سجد", frequency:28, verseNumber:114, verseArabic:"وَمَنْ أَظْلَمُ مِمَّن مَّنَعَ مَسَاجِدَ اللَّهِ", verseFr:"Qui est plus injuste que celui qui empêche qu'on invoque Allah dans les mosquées", verseRef:"Al-Baqara, 2:114", tip:"Masjid vient de sajada — se prosterner. La mosquée est la maison d'Allah." },

  // ========== NIVEAU 14 — La foi et ses piliers ==========
  { id:151, arabic:"تَوْحِيد", transliteration:"Tawḥīd", meaning:"Monothéisme — Unicité divine", root:"وحد", frequency:1, verseNumber:1, verseArabic:"قُلْ هُوَ اللَّهُ أَحَدٌ", verseFr:"Dis : Il est Allah, l'Unique", verseRef:"Al-Ikhlas, 112:1", tip:"Le Tawhid est le cœur de l'islam — tout part de l'unicité d'Allah." },
  { id:152, arabic:"شِرْك", transliteration:"Shirk", meaning:"Association — Polythéisme", root:"شرك", frequency:59, verseNumber:48, verseArabic:"إِنَّ اللَّهَ لَا يَغْفِرُ أَن يُشْرَكَ بِهِ", verseFr:"Allah ne pardonne pas qu'on Lui associe quelque chose", verseRef:"An-Nisa, 4:48", tip:"Le shirk est le seul péché irrémissible si on ne se repent pas avant la mort." },
  { id:153, arabic:"نِفَاق", transliteration:"Nifāq", meaning:"Hypocrisie", root:"نفق", frequency:13, verseNumber:8, verseArabic:"وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا بِاللَّهِ وَبِالْيَوْمِ الْآخِرِ وَمَا هُم بِمُؤْمِنِينَ", verseFr:"Parmi les gens, certains disent : nous croyons en Allah et au Jour Dernier, mais ils ne sont pas croyants", verseRef:"Al-Baqara, 2:8", tip:"Le munafiq (hypocrite) est pire que le mécréant dans le Coran." },
  { id:154, arabic:"كُفْر", transliteration:"Kufr", meaning:"Mécréance — Ingratitude", root:"كفر", frequency:525, verseNumber:6, verseArabic:"إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ", verseFr:"Ceux qui ont mécru, c'est égal pour eux que tu les avertisses ou non", verseRef:"Al-Baqara, 2:6", tip:"Kufr vient de kafara — couvrir. Le mécréant couvre la vérité de son cœur." },
  { id:155, arabic:"إِسْلَام", transliteration:"Islām", meaning:"Soumission — Paix", root:"سلم", frequency:8, verseNumber:19, verseArabic:"إِنَّ الدِّينَ عِندَ اللَّهِ الْإِسْلَامُ", verseFr:"La religion agréée d'Allah, c'est l'Islam", verseRef:"Aal Imran, 3:19", tip:"Islam = soumission à Allah. La même racine que Salam — paix." },
  { id:156, arabic:"مُسْلِم", transliteration:"Muslim", meaning:"Musulman — Soumis", root:"سلم", frequency:41, verseNumber:131, verseArabic:"إِذْ قَالَ لَهُ رَبُّهُ أَسْلِمْ قَالَ أَسْلَمْتُ لِرَبِّ الْعَالَمِينَ", verseFr:"Quand son Seigneur lui dit : soumets-toi, il dit : je me soumets au Seigneur des mondes", verseRef:"Al-Baqara, 2:131", tip:"Ibrahim fut le premier à se proclamer Muslim — tous les prophètes étaient muslims." },
  { id:157, arabic:"مُؤْمِن", transliteration:"Mu'min", meaning:"Croyant", root:"أمن", frequency:22, verseNumber:3, verseArabic:"الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ", verseFr:"Ceux qui croient à l'invisible", verseRef:"Al-Baqara, 2:3", tip:"Al-Mumin est aussi un nom d'Allah — Il est la Source de la foi." },
  { id:158, arabic:"كَافِر", transliteration:"Kāfir", meaning:"Mécréant", root:"كفر", frequency:154, verseNumber:6, verseArabic:"إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ", verseFr:"Ceux qui ont mécru, c'est égal pour eux", verseRef:"Al-Baqara, 2:6", tip:"Kafir = celui qui cache la vérité. Pas nécessairement un ennemi — peut être ignorant." },
  { id:159, arabic:"مُنَافِق", transliteration:"Munāfiq", meaning:"Hypocrite", root:"نفق", frequency:27, verseNumber:8, verseArabic:"وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا", verseFr:"Parmi les gens, certains disent : nous croyons", verseRef:"Al-Baqara, 2:8", tip:"La sourate Al-Munafiqun leur est entièrement dédiée — un avertissement sévère." },
  { id:160, arabic:"مُتَّقِي", transliteration:"Muttaqī", meaning:"Pieux — Craignant Allah", root:"وقي", frequency:53, verseNumber:2, verseArabic:"هُدًى لِّلْمُتَّقِينَ", verseFr:"Une guidance pour les pieux", verseRef:"Al-Baqara, 2:2", tip:"Le Coran est une guidance — mais seulement pour ceux qui ont la taqwa." },

  // ========== NIVEAU 15 — Mots du Coran final ==========
  { id:161, arabic:"بِسْمِ", transliteration:"Bismi", meaning:"Au nom de", root:"سمو", frequency:114, verseNumber:1, verseArabic:"بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", verseFr:"Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux", verseRef:"Al-Fatiha, 1:1", tip:"La Basmala précède 113 sourates — sauf At-Tawba. Elle est un bouclier." },
  { id:162, arabic:"قُلْ", transliteration:"Qul", meaning:"Dis !", root:"قول", frequency:332, verseNumber:1, verseArabic:"قُلْ هُوَ اللَّهُ أَحَدٌ", verseFr:"Dis : Il est Allah, l'Unique", verseRef:"Al-Ikhlas, 112:1", tip:"Qul est un ordre divin à Muhammad ﷺ — le mot le plus impératif du Coran." },
  { id:163, arabic:"يَا أَيُّهَا", transliteration:"Yā ayyuhā", meaning:"Ô vous !", root:"أيه", frequency:53, verseNumber:5, verseArabic:"يَا أَيُّهَا الَّذِينَ آمَنُوا", verseFr:"Ô vous qui croyez", verseRef:"Al-Maidah, 5:1", tip:"Chaque fois qu'Allah dit 'Ô vous qui croyez', une grande prescription suit." },
  { id:164, arabic:"إِنَّ", transliteration:"Inna", meaning:"Certes — En vérité", root:"أن", frequency:1705, verseNumber:153, verseArabic:"إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", verseFr:"Certes, Allah est avec les endurants", verseRef:"Al-Baqara, 2:153", tip:"Inna = affirmation forte. Allah insiste pour que nous croyions vraiment." },
  { id:165, arabic:"لَعَلَّ", transliteration:"La'alla", meaning:"Peut-être — Afin que", root:"لعل", frequency:129, verseNumber:183, verseArabic:"لَعَلَّكُمْ تَتَّقُونَ", verseFr:"Afin que vous soyez pieux", verseRef:"Al-Baqara, 2:183", tip:"La'alla exprime l'espoir divin — Allah espère que nous serons guidés." },
  { id:166, arabic:"سُبْحَان", transliteration:"Subḥān", meaning:"Gloire à — Exaltation", root:"سبح", frequency:41, verseNumber:1, verseArabic:"سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ", verseFr:"Gloire à Celui qui a fait voyager Son serviteur", verseRef:"Al-Isra, 17:1", tip:"Subhana = purifier de toute imperfection. Allah est au-dessus de tout défaut." },
  { id:167, arabic:"أَعُوذُ", transliteration:"A'ūdhu", meaning:"Je cherche refuge", root:"عوذ", frequency:7, verseNumber:4792, verseArabic:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", verseFr:"Dis : Je cherche refuge auprès du Seigneur de l'Aube", verseRef:"Al-Falaq, 113:1", tip:"Lire la Ta'awwudh avant le Coran protège des souffles de Satan." },
  { id:168, arabic:"أَمِين", transliteration:"Āmīn", meaning:"Ainsi soit-il — Amen", root:"أمن", frequency:0, verseNumber:6, verseArabic:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", verseFr:"Guide-nous dans le droit chemin", verseRef:"Al-Fatiha, 1:6", tip:"Amin n'est pas dans le texte coranique mais est dit après la Fatiha — c'est une invocation." },
  { id:169, arabic:"بَارَكَ", transliteration:"Bāraka", meaning:"Bénir — Accorder une bénédiction", root:"برك", frequency:32, verseNumber:1, verseArabic:"تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ", verseFr:"Béni soit Celui en la Main de Qui est le Royaume", verseRef:"Al-Mulk, 67:1", tip:"Tabarak = être béni en permanence. Allah est la source de toute bénédiction." },
  { id:170, arabic:"مَشَاءَ اللَّه", transliteration:"Mā shā' Allāh", meaning:"Ce qu'Allah a voulu", root:"شيء", frequency:1, verseNumber:39, verseArabic:"وَلَوْلَا إِذْ دَخَلْتَ جَنَّتَكَ قُلْتَ مَا شَاءَ اللَّهُ", verseFr:"Que n'as-tu dit, en entrant dans ton jardin : c'est ce qu'Allah a voulu", verseRef:"Al-Kahf, 18:39", tip:"Ma sha Allah protège contre le mauvais œil — une protection coranique réelle." },

  // ========== NIVEAU 16 — Mots du Paradis ==========
  { id:171, arabic:"فِرْدَوْس", transliteration:"Firdaws", meaning:"Firdaws — Le plus haut Paradis", root:"فردس", frequency:2, verseNumber:407, verseArabic:"أُولَٰئِكَ هُمْ وَارِثُو الْفِرْدَوْسِ هُمْ فِيهَا خَالِدُونَ", verseFr:"Ceux-là sont les héritiers du Firdaws, où ils demeureront éternellement", verseRef:"Al-Muminun, 23:11", tip:"Firdaws = le niveau le plus élevé du Paradis, sous le Trône d'Allah." },
  { id:172, arabic:"حُور", transliteration:"Ḥūr", meaning:"Houris — Compagnes du Paradis", root:"حور", frequency:4, verseNumber:3483, verseArabic:"وَزَوَّجْنَاهُم بِحُورٍ عِينٍ", verseFr:"Nous les aurons mariés à des Houris aux grands yeux", verseRef:"Ad-Dukhan, 44:54", tip:"Hur in = aux yeux brillants. Une récompense spirituelle et physique." },
  { id:173, arabic:"كَوْثَر", transliteration:"Kawthar", meaning:"Abondance — Fleuve du Paradis", root:"كثر", frequency:1, verseNumber:4767, verseArabic:"إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", verseFr:"Nous t'avons donné l'abondance", verseRef:"Al-Kawthar, 108:1", tip:"Al-Kawthar est un fleuve du Paradis réservé au Prophète ﷺ." },
  { id:174, arabic:"سِدْرَة", transliteration:"Sidra", meaning:"Jujubier — Limite extrême", root:"سدر", frequency:2, verseNumber:3530, verseArabic:"عِندَ سِدْرَةِ الْمُنتَهَىٰ", verseFr:"Près du Jujubier de la Limite extrême", verseRef:"An-Najm, 53:14", tip:"Sidrat al-Muntaha = la limite de la création. Le Prophète ﷺ l'a dépassée lors du Mi'raj." },
  { id:175, arabic:"عَرْش", transliteration:"'Arsh", meaning:"Trône divin", root:"عرش", frequency:33, verseNumber:129, verseArabic:"وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", verseFr:"Et Il est le Seigneur du Trône immense", verseRef:"At-Tawba, 9:129", tip:"Le Trône d'Allah est au-dessus des eaux — plus grand que tout l'univers." },
  { id:176, arabic:"كُرْسِيّ", transliteration:"Kursī", meaning:"Trône-estrade divin", root:"كرس", frequency:1, verseNumber:255, verseArabic:"وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ", verseFr:"Son Trône-estrade s'étend sur les cieux et la terre", verseRef:"Al-Baqara, 2:255", tip:"Le Kursi est le verset Al-Kursi — le plus grand verset du Coran." },
  { id:177, arabic:"مَلَك", transliteration:"Malak", meaning:"Ange", root:"ملك", frequency:88, verseNumber:98, verseArabic:"مَن كَانَ عَدُوًّا لِّجِبْرِيلَ", verseFr:"Quiconque est ennemi de Gabriel", verseRef:"Al-Baqara, 2:97", tip:"Les anges sont des créatures de lumière qui obéissent à Allah parfaitement." },
  { id:178, arabic:"جِبْرِيل", transliteration:"Jibrīl", meaning:"Gabriel — Ange de la révélation", root:"عبري", frequency:3, verseNumber:97, verseArabic:"مَن كَانَ عَدُوًّا لِّجِبْرِيلَ فَإِنَّهُ نَزَّلَهُ عَلَىٰ قَلْبِكَ", verseFr:"Car c'est lui qui l'a fait descendre sur ton cœur", verseRef:"Al-Baqara, 2:97", tip:"Jibril apporta la révélation au Prophète ﷺ pendant 23 ans." },
  { id:179, arabic:"إِبْلِيس", transliteration:"Iblīs", meaning:"Iblis — Satan", root:"بلس", frequency:11, verseNumber:34, verseArabic:"وَإِذْ قُلْنَا لِلْمَلَائِكَةِ اسْجُدُوا لِآدَمَ فَسَجَدُوا إِلَّا إِبْلِيسَ", verseFr:"Quand Nous dîmes aux anges : prosternez-vous devant Adam, ils se prosternèrent, sauf Iblis", verseRef:"Al-Baqara, 2:34", tip:"Iblis refusa par orgueil — le premier péché de l'histoire." },
  { id:180, arabic:"شَيْطَان", transliteration:"Shayṭān", meaning:"Diable — Démon", root:"شطن", frequency:88, verseNumber:168, verseArabic:"وَلَا تَتَّبِعُوا خُطُوَاتِ الشَّيْطَانِ", verseFr:"Et ne suivez pas les pas du Diable", verseRef:"Al-Baqara, 2:168", tip:"Shaytan vient de shatana — s'éloigner. Satan s'éloigne d'Allah et éloigne les autres." },

  // ========== NIVEAU 17 — Verbes et expressions essentiels ==========
  { id:181, arabic:"آمَنَ", transliteration:"Āmana", meaning:"Croire — Avoir la foi", root:"أمن", frequency:537, verseNumber:177, verseArabic:"لَّيْسَ الْبِرَّ أَن تُوَلُّوا وُجُوهَكُمْ قِبَلَ الْمَشْرِقِ وَالْمَغْرِبِ", verseFr:"La piété n'est pas de tourner vos visages vers l'Orient ou l'Occident", verseRef:"Al-Baqara, 2:177", tip:"Amana = croire avec le cœur, la langue et les actes — trois dimensions." },
  { id:182, arabic:"عَبَدَ", transliteration:"'Abada", meaning:"Adorer — Être serviteur", root:"عبد", frequency:275, verseNumber:5, verseArabic:"إِيَّاكَ نَعْبُدُ", verseFr:"C'est Toi seul que nous adorons", verseRef:"Al-Fatiha, 1:5", tip:"Abada = être esclave d'Allah. La servitude divine est la plus haute liberté." },
  { id:183, arabic:"خَلَقَ", transliteration:"Khalaqa", meaning:"Créer", root:"خلق", frequency:261, verseNumber:1, verseArabic:"اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ", verseFr:"Lis au nom de ton Seigneur qui a créé", verseRef:"Al-Alaq, 96:1", tip:"Le premier mot révélé était Iqra — le Coran commence par l'ordre de lire." },
  { id:184, arabic:"رَزَقَ", transliteration:"Razaqa", meaning:"Pourvoir — Accorder des subsistances", root:"رزق", frequency:123, verseNumber:3, verseArabic:"وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ", verseFr:"Et ils dépensent de ce que Nous leur avons accordé", verseRef:"Al-Baqara, 2:3", tip:"Allah est Ar-Razzaq — le Pourvoyeur. Toute subsistance vient de Lui." },
  { id:185, arabic:"هَدَى", transliteration:"Hadā", meaning:"Guider", root:"هدي", frequency:316, verseNumber:6, verseArabic:"اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", verseFr:"Guide-nous dans le droit chemin", verseRef:"Al-Fatiha, 1:6", tip:"On demande la guidance 17 fois par jour — c'est le besoin fondamental de l'homme." },
  { id:186, arabic:"غَفَرَ", transliteration:"Ghafara", meaning:"Pardonner — Couvrir", root:"غفر", frequency:234, verseNumber:173, verseArabic:"فَإِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ", verseFr:"Allah est Pardonneur et Miséricordieux", verseRef:"Al-Baqara, 2:173", tip:"Ghafara = couvrir d'un vêtement. Allah couvre nos péchés sans les exposer." },
  { id:187, arabic:"تَابَ", transliteration:"Tāba", meaning:"Se repentir — Revenir", root:"توب", frequency:87, verseNumber:222, verseArabic:"إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ", verseFr:"Allah aime ceux qui se repentent", verseRef:"Al-Baqara, 2:222", tip:"Taba = retourner. Se repentir c'est faire demi-tour vers Allah." },
  { id:188, arabic:"شَكَرَ", transliteration:"Shakara", meaning:"Être reconnaissant — Remercier", root:"شكر", frequency:75, verseNumber:7, verseArabic:"لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", verseFr:"Si vous êtes reconnaissants, Je vous donnerai davantage", verseRef:"Ibrahim, 14:7", tip:"La reconnaissance multiplie les bénédictions — une loi divine garantie." },
  { id:189, arabic:"صَبَرَ", transliteration:"Ṣabara", meaning:"Patienter — Endurer", root:"صبر", frequency:90, verseNumber:153, verseArabic:"إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", verseFr:"Allah est avec les patients", verseRef:"Al-Baqara, 2:153", tip:"Sabara = attacher. La patience attache le croyant à Allah dans les épreuves." },
  { id:190, arabic:"تَفَكَّرَ", transliteration:"Tafakkara", meaning:"Réfléchir — Méditer", root:"فكر", frequency:18, verseNumber:164, verseArabic:"لَآيَاتٍ لِّقَوْمٍ يَتَفَكَّرُونَ", verseFr:"Il y a là des signes pour des gens qui réfléchissent", verseRef:"Al-Baqara, 2:164", tip:"La réflexion est une ibada — contempler l'univers approche d'Allah." },

  // ========== NIVEAU 18 — Les 10 derniers mots ==========
  { id:191, arabic:"قَضَاء", transliteration:"Qaḍā'", meaning:"Décret divin — Jugement", root:"قضي", frequency:38, verseNumber:117, verseArabic:"وَإِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُن فَيَكُونُ", verseFr:"Quand Il décide d'une chose, Il lui dit : Sois, et elle est", verseRef:"Al-Baqara, 2:117", tip:"Kun fayakun = Sois et elle est. La création divine par la parole." },
  { id:192, arabic:"قَدَر", transliteration:"Qadar", meaning:"Destin — Mesure divine", root:"قدر", frequency:132, verseNumber:49, verseArabic:"إِنَّا كُلَّ شَيْءٍ خَلَقْنَاهُ بِقَدَرٍ", verseFr:"Nous avons tout créé avec mesure", verseRef:"Al-Qamar, 54:49", tip:"Le Qadar = tout est mesuré par Allah. Rien n'arrive par hasard." },
  { id:193, arabic:"لَوْح", transliteration:"Lawḥ", meaning:"Tablette — Table préservée", root:"لوح", frequency:2, verseNumber:4803, verseArabic:"فِي لَوْحٍ مَّحْفُوظٍ", verseFr:"Sur une Tablette préservée", verseRef:"Al-Buruj, 85:22", tip:"Al-Lawh al-Mahfuz = la Table préservée où tout est écrit depuis l'éternité." },
  { id:194, arabic:"قَلَم", transliteration:"Qalam", meaning:"Calame — Stylet", root:"قلم", frequency:4, verseNumber:1, verseArabic:"ن وَالْقَلَمِ وَمَا يَسْطُرُونَ", verseFr:"Nun. Par le calame et ce qu'ils écrivent", verseRef:"Al-Qalam, 68:1", tip:"La première création d'Allah fut le Qalam — il écrivit tout le destin." },
  { id:195, arabic:"عَهْد", transliteration:"'Ahd", meaning:"Alliance — Pacte — Promesse", root:"عهد", frequency:25, verseNumber:40, verseArabic:"الَّذِينَ يُوفُونَ بِعَهْدِ اللَّهِ", verseFr:"Ceux qui tiennent le pacte d'Allah", verseRef:"Ar-Ra'd, 13:20", tip:"L'Alliance avec Allah est le serment originel de l'âme humaine." },
  { id:196, arabic:"مِيثَاق", transliteration:"Mīthāq", meaning:"Pacte solennel", root:"وثق", frequency:25, verseNumber:83, verseArabic:"وَإِذْ أَخَذْنَا مِيثَاقَ بَنِي إِسْرَائِيلَ", verseFr:"Quand Nous avons pris le pacte solennel des fils d'Israël", verseRef:"Al-Baqara, 2:83", tip:"Le Mithaq est un engagement solennel — plus fort qu'un simple contrat." },
  { id:197, arabic:"بَيِّنَة", transliteration:"Bayyina", meaning:"Preuve claire — Évidence", root:"بين", frequency:19, verseNumber:1, verseArabic:"لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ الْبَيِّنَةُ", verseFr:"Ceux qui ont mécru parmi les gens du Livre ne se sépareraient pas jusqu'à ce que leur vienne la preuve", verseRef:"Al-Bayyina, 98:1", tip:"Bayyina = ce qui est clair et distinct. Le Coran est la bayyina ultime." },
  { id:198, arabic:"فَتْح", transliteration:"Fatḥ", meaning:"Victoire — Ouverture", root:"فتح", frequency:25, verseNumber:1, verseArabic:"إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا", verseFr:"Nous t'avons accordé une victoire éclatante", verseRef:"Al-Fath, 48:1", tip:"Fath = ouverture. La victoire de la Mecque fut une ouverture des cœurs." },
  { id:199, arabic:"نَصْر", transliteration:"Naṣr", meaning:"Victoire — Secours divin", root:"نصر", frequency:43, verseNumber:1, verseArabic:"إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", verseFr:"Quand vient le secours d'Allah et la victoire", verseRef:"An-Nasr, 110:1", tip:"La sourate An-Nasr fut révélée peu avant la mort du Prophète ﷺ." },
  { id:200, arabic:"خَاتِمَة", transliteration:"Khātima", meaning:"Conclusion — Sceau — Fin", root:"ختم", frequency:3, verseNumber:40, verseArabic:"مَّا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِّن رِّجَالِكُمْ وَلَٰكِن رَّسُولَ اللَّهِ وَخَاتَمَ النَّبِيِّينَ", verseFr:"Muhammad est le sceau des prophètes", verseRef:"Al-Ahzab, 33:40", tip:"Khatima = conclusion. Muhammad ﷺ est le sceau — après lui, plus de prophète." }
];

// Fausses réponses pour les quiz
const WRONG_ANSWERS = [
  "Lumière", "Paix", "Amour", "Force", "Sagesse", "Espoir", "Pardon",
  "Justice", "Bonheur", "Puissance", "Création", "Temps", "Eau", "Feu",
  "Terre", "Ciel", "Nuit", "Jour", "Âme", "Corps", "Vie", "Mort",
  "Bien", "Mal", "Vérité", "Mensonge", "Richesse", "Pauvreté",
  "Soleil", "Lune", "Étoile", "Montagne", "Mer", "Vent", "Prière",
  "Jeûne", "Pèlerinage", "Aumône", "Paradis", "Enfer", "Ange", "Prophète",
  "Messager", "Livre", "Verset", "Sourate", "Invocation", "Repentir",
  "Guidance", "Certitude", "Patience", "Gratitude", "Humilité", "Orgueil"
];

// Niveaux
const LEVELS = [
  { min:0,   max:9,   name:"Débutant",      icon:"🌱", desc:"Tu commences ton voyage coranique" },
  { min:10,  max:24,  name:"Chercheur",     icon:"🔍", desc:"Tu explores les mots fondamentaux" },
  { min:25,  max:49,  name:"Apprenti",      icon:"📖", desc:"Tu construis tes bases coraniques" },
  { min:50,  max:79,  name:"Intermédiaire", icon:"⭐", desc:"Le Coran commence à s'ouvrir à toi" },
  { min:80,  max:119, name:"Avancé",        icon:"🌟", desc:"Tu comprends l'essentiel du Coran" },
  { min:120, max:159, name:"Expert",        icon:"💎", desc:"Une maîtrise profonde et solide" },
  { min:160, max:199, name:"Maître",        icon:"🕌", desc:"Tu lis le Coran avec compréhension" },
  { min:200, max:200, name:"Hafidh honoré", icon:"👑", desc:"200 mots — le Coran est ta lumière" }
];
